name: powerboards_webserver
description: Simple web server for PowerBoards application
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
